[package]
name = "HelloRust"
version = "0.1.0"
edition = "2021"

[dependencies]
counter = "0.6.0"
num = "0.4.3"
reqwest = { version = "0.12.7", features = ["blocking"] }
select = "0.6.0"
text_io = "0.1.12"
unic-emoji-char = "0.9.0"
web-scraper = "0.1.0"
